name: templates Release
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: templates

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-templates: "true"
          base-path-to-templates: "./templates/src"
          generate-docs: "false"
